#!/usr/bin/python
# -*- coding: latin-1 -*-

# Copyright 2013-2015 Pervasive Displays, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#   http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.  See the License for the specific language
# governing permissions and limitations under the License.

from __future__ import print_function

import os
import sys

from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont
from datetime import datetime
from dateutil.tz import tzlocal
import time
from papirus import Papirus

papirus = 0

# Check EPD_SIZE is defined
EPD_SIZE=0.0
if os.path.exists('/etc/default/epd-fuse'):
    exec(open('/etc/default/epd-fuse').read())
if EPD_SIZE == 0.0:
    print("Please select your screen size by running 'papirus-config'.")
    sys.exit()

# Running as root only needed for older Raspbians without /dev/gpiomem
if not (os.path.exists('/dev/gpiomem') and os.access('/dev/gpiomem', os.R_OK | os.W_OK)):
    user = os.getuid()
    if user != 0:
        print("Please run script as root")
        sys.exit()

WHITE = 1
BLACK = 0

#CLOCK_FONT_FILE = '/usr/share/fonts/truetype/freefont/FreeMonoBold.ttf'
#DATE_FONT_FILE  = '/usr/share/fonts/truetype/freefont/FreeMono.ttf'
CLOCK_FONT_FILE = '/home/pi/all_fonts_myoffice/XO_Oriel/XO_Oriel/TTF/XO_Oriel_CN_Nu.ttf'
DATE_FONT_FILE  = '/home/pi/all_fonts_myoffice/XO_Oriel/XO_Oriel/TTF/XO_Oriel_CN_Nu.ttf'
WIFI_FONT_FILE  = '/home/pi/all_fonts_myoffice/XO_Oriel/XO_Oriel/TTF/XO_Oriel_Nu.ttf'

def main(argv):

    """main program - draw and display time and date"""

    papirus = Papirus(rotation = int(argv[0]) if len(sys.argv) > 1 else 0)

    print('panel = {p:s} {w:d} x {h:d}  version={v:s} COG={g:d} FILM={f:d}'.format(p=papirus.panel, w=papirus.width, h=papirus.height, v=papirus.version, g=papirus.cog, f=papirus.film))

    papirus.clear()

    demo(papirus)


def demo(papirus):
    """simple partial update demo - draw a clock"""

    # initially set all white background
    image = Image.new('1', papirus.size, WHITE)

    # prepare for drawing
    draw = ImageDraw.Draw(image)
    width, height = image.size

    clock_font_size = int((width - 4)/(8*0.65))-10      # 8 chars HH:MM:SS
    clock_font = ImageFont.truetype(CLOCK_FONT_FILE, clock_font_size)
    date_font_size = int((width - 10)/(10*0.65))-10     # 10 chars YYYY-MM-DD
    date_font = ImageFont.truetype(DATE_FONT_FILE, date_font_size)
    wifi_font_size = int((width - 10)/(11*0.65))-10     # 10 chars YYYY-MM-DD
    wifi_font = ImageFont.truetype(WIFI_FONT_FILE, wifi_font_size)

    # clear the display buffer
    draw.rectangle((0, 0, width, height), fill=WHITE, outline=WHITE)
    previous_second = 0
    previous_day = 0
    ssid_old = ""

    while True:
        now = datetime.now(tzlocal())
        ssid=os.popen("iwgetid -r").read()
        nof=os.popen("find /mnt/usb_share -type f | wc -l").read()
        temp=os.popen("/home/pi/temp.sh").read()
        if not temp:
            temp="0"
        #batt=os.popen("/home/pi/MiTemperature2/LYWSD03MMC.py -d A4:C1:38:FC:26:CD -c 1 -r -b | grep \"Battery level:\"  | sed \"s/Battery level: //\"").read()

        if now.day != previous_day:
            draw.rectangle((2, 2, width - 2, height - 2), fill=WHITE, outline=BLACK)
            draw.text((10, clock_font_size + 10), '{y:04d}.{m:02d}.{d:02d}               file(s)'.format(y=now.year, m=now.month, d=now.day), fill=BLACK, font=date_font)
            previous_day = now.day
            ssid_old = ""
        else:
            draw.rectangle((5, 10, width - 5, 10 + clock_font_size), fill=WHITE, outline=WHITE)

        draw.text((10, 10), '{h:02d}:{m:02d}   {temp:2d}\xb0C   {nof:03d}'.format(nof=int(nof),h=now.hour, m=now.minute, s=now.second, temp=int(temp)), fill=BLACK, font=clock_font)

        if ssid != ssid_old:
            draw.rectangle((5, 85, width - 5, 85-wifi_font_size ), fill=WHITE, outline=WHITE)
            if len(ssid) < 1 :
                ssid='(not connected)'
            draw.text((10, clock_font_size + 20 + date_font_size),'wifi: '+ssid, fill=BLACK, font=wifi_font)
            ssid_old = ssid

        # display image on the panel
        papirus.display(image)
        if previous_second > 15:
            previous_second = 0
            papirus.clear()
            papirus.update()
        else:
            papirus.partial_update()
        previous_second = previous_second+1
	#print ('{h:02d}:{m:02d}:{s:02d}'.format(h=now.hour, m=now.minute, s=now.second))
        time.sleep(60)

# main
if "__main__" == __name__:
    if len(sys.argv) < 1:
        sys.exit('usage: {p:s}'.format(p=sys.argv[0]))

    try:
        main(sys.argv[1:])
    except KeyboardInterrupt:
        sys.exit('interrupted')
        pass
